name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  merge_group:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: rustup update
        run: rustup update
      - name: Show cargo version
        run: cargo --version
      - name: Show rustc version
        run: rustc --version
      - name: Install cross
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
      - name: Cargo clean
        run: cargo clean
      - name: Show Cargo.lock hash
        run: sha256sum Cargo.lock
      - name: Fetch
        run: |
          cargo fetch --locked
      - name: Build x86_64-unknown-linux-gnu
        run: |
          cargo build --target=x86_64-unknown-linux-gnu --release --frozen
      - name: Test x86_64-unknown-linux-gnu including cli
        run: |
          cargo test --target=x86_64-unknown-linux-gnu --release --frozen --workspace --features cli_tests -- --nocapture --test-threads 1
      - name: Build x86_64-unknown-linux-musl
        run: |
          cargo clean && cross build --target=x86_64-unknown-linux-musl --release --frozen
      - name: Test x86_64-unknown-linux-musl including cli
        run: |
          cross test --target=x86_64-unknown-linux-musl --release --frozen --workspace --features cli_tests -- --nocapture --test-threads 1
      - name: Build armv7-unknown-linux-musleabihf
        run: |
          cargo clean && cross build --target=armv7-unknown-linux-musleabihf --release --frozen
      - name: Test armv7-unknown-linux-musleabihf
        run: |
          cross test --target=armv7-unknown-linux-musleabihf --release --frozen --workspace -- --nocapture --test-threads 1
      - name: Build aarch64-unknown-linux-musl
        run: |
          cargo clean && cross build --target=aarch64-unknown-linux-musl --release --frozen
      - name: Test aarch64-unknown-linux-musl
        run: |
          cross test --target=aarch64-unknown-linux-musl --release --frozen --workspace -- --nocapture --test-threads 1
